###
POST http://localhost:3003/purchases/
Content-Type: application/json

{
    "name":"carlos",
    "date":"2022-10-02",
    "purchaseItems":[
        {
            "id":16,
            "quantity":2
        }
]
}
