###
GET http://localhost:3003/products

### 
POST http://localhost:3003/purchases
Content-Type: application/json

{   
    "name":"jao",
    "date":"25/11/2022",
    "purchasedItems":[
        {
            "id":16,
            "quantity":159
        },
        {
            "id":18,
            "quantity":1590
        }
    ]

    
   
}